# Generated by Django 5.1.7 on 2025-03-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='watchlist',
            table='watchlist',
        ),
    ]
