# Generated by Django 5.1.7 on 2025-03-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_watchlist_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'managed': False},
        ),
    ]
