# Generated by Django 5.1.7 on 2025-04-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_watchlist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('liked_movie_ids', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
